# Generated by Django 2.0.1 on 2018-02-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=10)),
                ('ip_list', models.TextField()),
                ('smtpauth', models.CharField(max_length=5)),
            ],
        ),
    ]
